apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  namespace: argocd
data:
  url: https://argocd.127.0.0.1.nip.io:32198/