apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml  
  - main-namespace.yaml
  - user-namespace.yaml
  - test-namespace.yaml
  - https://raw.githubusercontent.com/googleforgames/agones/release-1.21.0/install/yaml/install.yaml
  - supertux-gameserver.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
    path: argocd-rbac-cm.yaml
  - target:
      version: v1
      kind: Service
      name: argocd-server
    path: argocd-server.yaml